apiVersion: v1
kind: Pod
spec:
${PODMAN_VOLUMES_BLOCK}
  containers:
    - name: jnlp
      image: ${RUNTIME_IMAGE}
      imagePullPolicy: Always
      securityContext:
        runAsUser: 0
        privileged: true
${PROC_MOUNT}
${PODMAN_VOLUME_MOUNTS_BLOCK}
      env:
        - name: COIN_REGISTRY_PREFIX
          value: "${REGISTRY_PREFIX}"
        - name: BUILDKIT_HOST
          value: "unix:///tmp/buildkit.sock"
        - name: COIN_BUILD_ENGINE
          value: "${COIN_BUILD_ENGINE}"
      resources:
        requests:
          cpu: "${JNLP_CPU_REQUEST}"
          memory: "${JNLP_MEMORY_REQUEST}"
        limits:
          memory: "${JNLP_MEMORY_LIMIT}"
