version: 1

coin:
  template: java-gradle
  templateVersion: "1.0.0"
  mode: standard
  versioning:
    mode: corporate
    tagPrefix: "v"

project:
  name: my-service
  stack: java-gradle

runtime:
  java: "17"

container:
  port: 8080
  command: ["java", "-jar", "/app/app.jar"]

pipeline:
  test:
    enabled: true
  build:
    enabled: true
    target: container
    dockerfileTemplate: java-gradle
  publish:
    enabled: true
    registry: nexus-docker
    when: tag

quality:
  sonar:
    enabled: false
    projectKey: my-service

deploy:
  enabled: false
