/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (PostgreSQL ping) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/golden-paths/{name}/versions/{version}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve immutable manifest for GP release */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example go-app */
                    name: string;
                    /** @example 1.0.0 */
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resolved manifest */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Manifest"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Version below catalog minimum */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description GP release not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/builds/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report build telemetry */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BuildReport"];
                };
            };
            responses: {
                /** @description Accepted */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard counts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardStats"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects (latest GP binding) */
        get: {
            parameters: {
                query?: {
                    goldenPath?: string;
                    version?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectList"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/golden-paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published GP releases */
        get: {
            parameters: {
                query?: {
                    /** @example go-app */
                    name?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description GP release list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GPReleaseList"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/components/{type}/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish component version (append-only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example executor */
                    type: string;
                    /** @example coin-executor */
                    name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PublishComponentVersion"];
                };
            };
            responses: {
                /** @description Published */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Version already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/golden-paths/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish GP release (append-only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example go-app */
                    name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PublishGPRelease"];
                };
            };
            responses: {
                /** @description Published */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid composition or compatibility failure */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description GP version already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/golden-paths/{name}/versions/{version}/blast-radius": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blast radius — projects on GP versions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example go-app */
                    name: string;
                    /** @example 1.0.2 */
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Blast radius counts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BlastRadius"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Manifest: {
            /** @example 1 */
            manifestVersion: number;
            /** @example sha256:abc... */
            manifestHash: string;
            goldenPath: {
                name: string;
                version: string;
            };
            executor: {
                version?: string;
                url?: string;
                sha256?: string;
            };
            runtime: {
                image?: string;
                digest?: string;
            };
            pipeline: {
                stages?: Record<string, never>[];
            };
            validateSchema?: components["schemas"]["ContentRef"];
            dockerfileTemplate?: components["schemas"]["ContentRef"];
            credentials?: {
                [key: string]: string;
            };
        };
        ContentRef: {
            gitRef: string;
            path: string;
            sha256: string;
        };
        BuildReport: {
            project: string;
            goldenPath: string;
            version: string;
            branch?: string;
            buildUrl?: string;
            /** @enum {string} */
            result: "success" | "failure" | "aborted";
        };
        PublishComponentVersion: {
            /** @example 0.2.0 */
            version: string;
            metadata?: {
                [key: string]: unknown;
            };
            contentRef?: {
                [key: string]: unknown;
            };
            /** @example platform-bot */
            actor?: string;
        };
        PublishGPRelease: {
            /** @example 1.0.1 */
            version: string;
            /**
             * @example {
             *       "executor": "0.1.0",
             *       "agent": "1.22.5",
             *       "pipeline": "2.1.0",
             *       "validate": "1.0.0",
             *       "dockerfile": "1.0.0"
             *     }
             */
            composition: {
                [key: string]: string;
            };
            /** @example go-app/v1.0.1 */
            gitExportTag?: string;
            actor?: string;
        };
        BlastRadius: {
            goldenPath: string;
            version: string;
            onThisVersion: number;
            onOtherVersions: number;
            onOlderVersions: number;
            totalOnGP: number;
            byVersion: {
                version: string;
                count: number;
            }[];
        };
        DashboardStats: {
            projects: number;
            gpReleases: number;
            buildReports: number;
            goldenPaths: number;
        };
        Project: {
            name: string;
            goldenPath: string;
            version: string;
            gitUrl?: string;
            /** Format: date-time */
            lastSeenAt: string;
        };
        ProjectList: {
            items: components["schemas"]["Project"][];
        };
        GPRelease: {
            name: string;
            version: string;
            status: string;
            manifestHash?: string;
            manifestUrl?: string;
            gitExportTag?: string;
            /** Format: date-time */
            createdAt: string;
        };
        GPReleaseList: {
            items: components["schemas"]["GPRelease"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
