schemaVersion: 3
name: go-app-docker
kind: golden-path
validateSchema: schemas/config.v2.schema.json

parameters:
pipeline:
  stages:
    - id: ul91ak
      name: Validate
      steps:
        - action: run
          run:
            engine: dockerfile
            output: validate
            dockerfile:
              path: Dockerfile
    - id: 45s9cv
      name: Test
      steps:
        - action: run
          run:
            engine: dockerfile
            output: test
            dockerfile:
              path: Dockerfile
    - id: t6onxo
      name: Build
      steps:
        - action: build
          build:
            id: ffubk4
            type: image
            engine: dockerfile
            dockerfile:
              path: Dockerfile
    - id: 99j5lg
      name: Publish
      steps:
        - action: publish
          publish:
            buildStepId: ffubk4
