name: go-app-bp
kind: gp-content
capabilities:
  deliverables:
    - image
controls:
  skipTests:
    type: boolean
    default: false
  publishMode:
    type: choice
    values: [auto, never, force]
    default: auto
  snapshot:
    type: boolean
    default: true
  bump:
    type: choice
    values: [none, patch, minor, major]
    default: none
build:
  engine: buildpack
  buildpack:
    builder: nexus:8082/coin-docker/paketo-builder-jammy-base
    cacheRefTemplate: "{{registryHost}}/coin-cache/{{project}}:buildpack"
pipeline:
  stages:
    - id: validate
      name: Validate
    - id: test
      name: Test
    - id: build
      name: Build
    - id: publish
      name: Publish
      when: tag
validateSchema:
  artifactKey: schemas/config.v2.schema.json
