schemaVersion: 2
name: go-app
kind: gp-content

capabilities:
  deliverables:
    - image
    - artifact

build:
  engine: buildkit
  buildkit:
    targets:
      validate: validate
      test: test
      image: runtime
      artifact: artifact
    cacheRefTemplate: "{{registryHost}}/coin-cache/{{project}}:buildkit"

pipeline:
  stages:
    - id: validate
      name: Validate
    - id: test
      name: Test
    - id: build
      name: Build
    - id: publish
      name: Publish

artifacts:
  validateSchema: schemas/config.v2.schema.json
  containerfile: dockerfiles/Containerfile
