coin:
  goldenPath: go-app
  version: "*"
  resolve: file
  # manifestFile: .coin/manifest.local.yaml

jenkins:
  credentials:
    docker: nexus-docker

project:
  name: my-service
  artifactId: my-service
  groupId: com.example.team
